services:
  calc_service:
    container_name: calc_service
    build: 
      context: .
    env_file:
      - ./config.env
    ports:
      - "9090:9090"
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "8085:8080"
    volumes:
      - ./api/calc.swagger.yaml:/usr/share/nginx/html/swagger/calc.swagger.yaml
    environment:
      API_URL: swagger/calc.swagger.yaml