---
swagger: "2.0"
info:
  version: "version not set"
  title: "calc/calc.proto"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /api/v1/calculate:
    post:
      tags:
      - "CalcService"
      operationId: "CalcService_Calculate"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/calcCalculateRequest"
        x-exportParamName: "Body"
      responses:
        "200":
          description: "A successful response."
          schema:
            $ref: "#/definitions/calcCalculateResponse"
        default:
          description: "An unexpected error response."
          schema:
            $ref: "#/definitions/runtimeError"
definitions:
  calcCalculateRequest:
    type: "object"
    properties:
      expression:
        type: "string"
  calcCalculateResponse:
    type: "object"
    properties:
      result:
        type: "number"
        format: "float"
    example:
      result: 0.8008282
  protobufAny:
    type: "object"
    properties:
      type_url:
        type: "string"
      value:
        type: "string"
        format: "byte"
        pattern: "^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$"
  runtimeError:
    type: "object"
    properties:
      error:
        type: "string"
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
      details:
        type: "array"
        items:
          $ref: "#/definitions/protobufAny"
